<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Oppaku.Core\Oppaku.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\assets\logo.ico</ApplicationIcon>
    <AssemblyName>OppakuGUI</AssemblyName>
    <Version>0.7.1</Version>
    <AssemblyVersion>0.7.1.0</AssemblyVersion>
    <FileVersion>0.7.1.0</FileVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

</Project>
